config/routes.rb
IsoconfApp::Application.routes.draw do
  resources :registrations
  resources :payments do
      collection do
        get 'confpay'
      end
  end

  devise_for :users

  devise_scope :user do
    root to: 'static_pages#home'
    match '/registrations/user', to: 'devise/registrations#create', via: :post
  end

  match '/home', to: 'static_pages#home', via: 'get'
  match '/program', to: 'static_pages#program', via: 'get'
  match '/venue', to: 'static_pages#venue', via: 'get'
  match '/organizers', to: 'static_pages#organizers', via: 'get'
  match '/dates', to: 'static_pages#dates', via: 'get'
  match '/fees', to: 'static_pages#fees', via: 'get'
  match '/pay', to: 'static_pages#payment', via: 'get'
  match '/social', to: 'static_pages#social', via: 'get'
  match '/sponsors', to: 'static_pages#sponsors', via: 'get'
  match '/abstracts', to: 'static_pages#abstract-submittion', via: 'get'

end

app/views/payment_confirmation/confirmation_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h3>Isotopes 2015 Conference</h3>
    <p>
      <%= @payed_user.title %> <%= @payed_user.lastName %> <%= @payed_user.firstName %>, <br />
      This is to confirm you have successfully signed up to Isotopes 2015 conference!<br />
      Here is a summary of your registration:<br />
      <ul>
        <li>Room type and fee:
        <% if @roomPrice > 0 %>
          <%= @roomType %>, <%= @roomPrice %> € (Euro)
        <% else %>
          Not Applicable
        <% end %>
        </li>
        <li>Conference participation fee: <%= @confPrice %>
          <% if not @confPrice.instance_of? String %>
            € (Euro)
          <% end %>
        </li>
      </ul>
    </p>
    <p>We look forward to seeing you!</p>

    <h5>* This is an automated email, do not reply</h5>
  </body>
</html>

app/views/payment_confirmation/confirmation_email.text.erb
Isotopes 2015 Conference
=========================

<%= @payed_user.title %> <%= @payed_user.lastName %> <%= @payed_user.firstName %>,
You have successfully signed up to Isotopes 2015 conference!
Here is a summary of your registration:
Room type and fee: <% if @roomPrice > 0 %> <%= @roomType %>, <%= @roomPrice %> € (Euro) <% else %>Not Applicable<% end %>
Conference participation fee: <%= @confPrice %><% if not @confPrice.instance_of? String %> € (Euro)<% end %>

We look forward to seeing you!

* This is an automated email, do not reply

app/views/payment_confirmation/confirmation_unsucessful.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h3>Isotopes 2015 Conference - Payment Failure</h3>
    <p>
      Hi Nurit,<br />
      Please note that <%= @payed_user.title %> <%= @payed_user.lastName %> <%= @payed_user.firstName %>
       couldn't complete payment.<br />
      Error code from credit 2000 is: <%= @errorCode %> <br />
      You can contact him by email <%= mail_to @payed_user.email %>, and
      view and edit his registration form is <%= link_to "here", edit_registration_url(@payed_user) %>.
    </p>
  </body>
</html>