config/routes.rb
IsoconfApp::Application.routes.draw do
  resources :registrations
  resources :payments do
      collection do
        get 'confpay'
      end
  end

  devise_for :users

  devise_scope :user do
    root to: 'static_pages#home'
    match '/registrations/user', to: 'devise/registrations#create', via: :post
  end

  match '/home', to: 'static_pages#home', via: 'get'
  match '/program', to: 'static_pages#program', via: 'get'
  match '/venue', to: 'static_pages#venue', via: 'get'
  match '/organizers', to: 'static_pages#organizers', via: 'get'
  match '/dates', to: 'static_pages#dates', via: 'get'
  match '/fees', to: 'static_pages#fees', via: 'get'
  match '/pay', to: 'static_pages#payment', via: 'get'
  match '/social', to: 'static_pages#social', via: 'get'
  match '/sponsors', to: 'static_pages#sponsors', via: 'get'
  match '/abstracts', to: 'static_pages#abstract-submittion', via: 'get'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    &copy 2014 All rights reserved - Gilad Rainer
  </small>
  <nav>
    <ul>
      <% if user_signed_in? %>
        <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Admin Login", new_user_session_path %></li>
      <% end %>
    </ul>
  </nav>

</footer>

app/views/layouts/_header.html.erb
<%= image_tag("banner_final.png", class: 'center-block', width: '940') %>
<!-- h1 class="center">Welcome to Isotopes 2015 Conference!</h1 -->

app/views/layouts/_menu.html.erb
<ul class="nav nav-tabs nav-stacked">
	<li class="<%= is_active?(home_path) %>"><%= link_to "Home", home_path %></li>
	<li class="<%= is_active?(venue_path) %>"><%= link_to "Conference Venue", venue_path %></li>
	<li class="<%= is_active?(program_path) %>"><%= link_to "Program", program_path %></li>
	<li class="<%= is_active?(dates_path) %>"><%= link_to "Important Dates", dates_path %></li>
	<li class="<%= is_active?(organizers_path) %>"><%= link_to "Organizing Committee", organizers_path %></li>
	<li class="<%= is_active?(social_path) %>"><%= link_to "Social program", social_path %></li>
	<li class="<%= is_active?(fees_path) %>"><%= link_to "Registration Fees", fees_path %></li>
	<li class="<%= is_active?(new_registration_path) %>"><%= link_to "Registration + Payment", new_registration_path %></li>

<% if false %>
	<li class="<%= is_active?(pay_path) %>"><%= link_to "Payment", pay_path %></li>
<% end %>

	<li class="<%= is_active?(abstracts_path) %>"><%= link_to "Abstract Form", abstracts_path %></li>
	<% if user_signed_in? %>
		<li class="<%= is_active?(registrations_path) %>">
				<%= link_to "Download Reg Form Data", registrations_path, class: "admin" %>
		</li>
	<% end %>

	<li class="<%= is_active?(sponsors_path) %>"><%= link_to "Sponsors", sponsors_path %></li>

</ul>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body class="fill">
	<div class="header">
		<%= render 'layouts/header' %>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-sm-3 col-md-3 sidemenu">
				<%= render 'layouts/menu' %>
			</div>

			<div class="col-sm-9 col-md-9 content">
				<% flash.each do |key, value| %>
					<div class="alert alert-<%= key %>"><%= value %></div>
				<% end %>
				<%= yield %>
			</div>
		</div>
	
	</div>

	<div class="footer">
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>